;; Code generated by update-protocol-version. DO NOT EDIT.
;;
;; SDK Protocol Version for the Copilot SDK.
;; This must match the version expected by the copilot-agent-runtime server.

(ns copilot.sdk-protocol-version)

(def sdk-protocol-version
  "The SDK protocol version number. Must match the server's expected version."
  2)

(defn get-sdk-protocol-version
  "Returns the SDK protocol version."
  []
  sdk-protocol-version)
